import { ChallengeDifficulty, ChallengeFrequency, ActivityCategory } from '../types';

export interface SeedChallenge {
  title: string;
  description: string;
  category: ActivityCategory;
  difficulty: ChallengeDifficulty;
  points: number;
  estimatedSavingKg: number;
  frequency: ChallengeFrequency;
  isActive: boolean;
}

export const SEED_CHALLENGES: SeedChallenge[] = [
  {
    title: 'Meat-Free Day',
    description: 'Avoid all meat products for one full day and focus on a plant-based diet.',
    category: 'food',
    difficulty: 'easy',
    points: 50,
    estimatedSavingKg: 3.0,
    frequency: 'daily',
    isActive: true,
  },
  {
    title: 'Veggie Week',
    description: 'Maintain a vegetarian or vegan diet for an entire week.',
    category: 'food',
    difficulty: 'hard',
    points: 250,
    estimatedSavingKg: 21.0,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'Bus or Train Commute',
    description: 'Take public transit instead of driving your personal car to work or school.',
    category: 'transportation',
    difficulty: 'medium',
    points: 75,
    estimatedSavingKg: 4.5,
    frequency: 'daily',
    isActive: true,
  },
  {
    title: 'Active Commuting Week',
    description: 'Walk, cycle, or use public transport for all commutes this week.',
    category: 'transportation',
    difficulty: 'hard',
    points: 300,
    estimatedSavingKg: 25.0,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'Unplug Standby Devices',
    description: 'Unplug chargers, TVs, and electronics on standby before going to bed.',
    category: 'electricity',
    difficulty: 'easy',
    points: 30,
    estimatedSavingKg: 0.5,
    frequency: 'daily',
    isActive: true,
  },
  {
    title: 'Eco-Wash Only',
    description: 'Use the eco or cold setting on your washing machine for all loads this week.',
    category: 'electricity',
    difficulty: 'medium',
    points: 100,
    estimatedSavingKg: 2.0,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'Quick Shower Challenge',
    description: 'Keep your shower under 5 minutes to conserve hot water and heating energy.',
    category: 'water',
    difficulty: 'easy',
    points: 40,
    estimatedSavingKg: 0.8,
    frequency: 'daily',
    isActive: true,
  },
  {
    title: 'Navy Showers Week',
    description: 'Turn off the water while soaping/shampooing during showers for an entire week.',
    category: 'water',
    difficulty: 'medium',
    points: 120,
    estimatedSavingKg: 4.0,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'No Plastic Purchases',
    description: 'Avoid purchasing any products packaged in single-use plastic today.',
    category: 'shopping',
    difficulty: 'medium',
    points: 60,
    estimatedSavingKg: 1.0,
    frequency: 'daily',
    isActive: true,
  },
  {
    title: 'Zero-Waste Grocery Shop',
    description: 'Use reusable bags, containers, and buy in bulk for your grocery shopping.',
    category: 'shopping',
    difficulty: 'medium',
    points: 80,
    estimatedSavingKg: 1.5,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'Second-Hand Style',
    description: 'Purchase second-hand/thrifted clothes instead of buying new fast-fashion items.',
    category: 'shopping',
    difficulty: 'hard',
    points: 200,
    estimatedSavingKg: 8.0,
    frequency: 'monthly',
    isActive: true,
  },
  {
    title: 'No Screen Sunday',
    description:
      'Turn off your computer, console, and TV to spend a day off-screen conserving energy.',
    category: 'electricity',
    difficulty: 'medium',
    points: 100,
    estimatedSavingKg: 1.5,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'Bicycle Short Trips',
    description: 'Use a bicycle for all trips under 5 km this week.',
    category: 'transportation',
    difficulty: 'medium',
    points: 150,
    estimatedSavingKg: 6.0,
    frequency: 'weekly',
    isActive: true,
  },
  {
    title: 'Leftover Love',
    description: 'Eat leftovers or compost all food scraps to achieve zero food waste today.',
    category: 'food',
    difficulty: 'easy',
    points: 40,
    estimatedSavingKg: 1.2,
    frequency: 'daily',
    isActive: true,
  },
  {
    title: 'Fix a Leak',
    description: 'Inspect and fix any running toilet, dripping tap, or pipe leak in your home.',
    category: 'water',
    difficulty: 'medium',
    points: 150,
    estimatedSavingKg: 10.0,
    frequency: 'one-time',
    isActive: true,
  },
];
